sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -y --allow-unauthenticated
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" docker-engine

before_script:
  - docker build --force-rm=true -t deeky666/docker-compose:latest .
  - docker run deeky666/docker-compose docker-compose version
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push deeky666/docker-compose

script: true

matrix:
  fast_finish: true
